### ISSUE TITLE
Unterteilung der Fragen nach Tags

### ISSUE THREAD

**Issue by manuel-brs** [SE-TINF22B2/G6-SimpleQ#32]
Das System muss die Möglichkeit bieten die zu erstellende Frage nach unterschiedlichen Tags einzuteilen. Dabei kann zwischen bereits existierenden Tags gewählt werden oder falls der gewünschte Tag nicht existiert, kann ein neuer Tag erstellt werden.

**Comment by Integraluminium** [comment]
❌ Geschlossen, da anderes Issue dieses Thema bereits abdeckt.
