### ISSUE TITLE
Hervorhebung von automatisch generierten Antworten

### ISSUE THREAD

**Issue by MichalskyL** [SE-TINF22B2/G6-SimpleQ#45]
#### Beschreibung
Das System muss fähig sein automatisch generierte Antworten hervorzuheben. Alle User, die diese Antwort betrachten müssen eindeutig erkennen können, dass die Antwort automatisch generiert wurde. 
Automatisch generierte Antworten werden durch farbliche Kennzeichnung und Symbolik gekennzeichnet.

#### Abnahmekriterien
- [x] automatisch generierte Antworten werden hervorgehoben

#### Arbeitspakete
1. #79

**Comment by Integraluminium** [comment]
Anpassung an gemeinsame Besprechung vom 13.11.23
